parameters:

  ongr.repository_crawler.crawler.class: ONGR\RepositoryCrawlerBundle\Crawler\Crawler

services:

  ongr.repository_crawler.crawler:
      class: %ongr.repository_crawler.crawler.class%
      calls:
          - [setDispatcher, [@event_dispatcher]]
      scope: container
