parameters:

  ongr.repository_crawler.crawler.class: ONGR\RepositoryCrawlerBundle\Crawler\Crawler
  ongr.repository_crawler.process_document.class: ONGR\RepositoryCrawlerBundle\Event\CrawlerConsumeEventHandler
  ongr.repository_crawler.crawler_context.class: ONGR\RepositoryCrawlerBundle\Crawler\RepositoryCrawlerContext
  ongr.repository_crawler.crawler_source.class: ONGR\RepositoryCrawlerBundle\Event\CrawlerSourceEventHandler
  ongr_connections.pipeline_factory.class: ONGR\ConnectionsBundle\Pipeline\PipelineFactory
  ongr_connections.pipeline_factory.pipeline_class: ONGR\ConnectionsBundle\Pipeline\Pipeline


services:

  ongr.repository_crawler.crawler:
      class: %ongr.repository_crawler.crawler.class%
      calls:
          - [setPipelineFactory, [ @ongr_connections.pipeline_factory ] ]
      scope: container

  ongr_connections.pipeline_factory:
      class: %ongr_connections.pipeline_factory.class%
      calls:
          - [ setDispatcher, [ @event_dispatcher ] ]
          - [ setClassName, [ %ongr_connections.pipeline_factory.pipeline_class% ] ]

  ongr.repository_crawler.crawler_context:
      class: %ongr.repository_crawler.crawler_context.class%

  ongr.pipeline.repository_crawler.crawler_process_document:
      class: %ongr.repository_crawler.process_document.class%
      tags:
          - { name: kernel.event_listener, event: 'ongr.pipeline.ongr.repository_crawler.processEvent.consume', method: 'onConsume' }

  ongr.pipeline.repository_crawler.crawler_source:
      class: %ongr.repository_crawler.crawler_source.class%
      tags:
          - { name: kernel.event_listener, event: 'ongr.pipeline.ongr.repository_crawler.processEvent.source', method: 'onSource' }
