parameters:
    ongr_connections.pipeline_factory.class: ONGR\ConnectionsBundle\Pipeline\PipelineFactory
    ongr_connections.pipeline_factory.pipeline_class: ONGR\ConnectionsBundle\Pipeline\Pipeline

    ongr_repository_crawler.crawler.class: ONGR\RepositoryCrawlerBundle\Crawler\Crawler
    ongr_repository_crawler.crawler.source.class: ONGR\RepositoryCrawlerBundle\Event\CrawlerRepositorySource

services:
    # Crawler service.
    ongr_repository_crawler.crawler:
        class: %ongr_repository_crawler.crawler.class%
        calls:
            - [setPipelineFactory, [ @ongr_connections.pipeline_factory ] ]

    # Factory.
    ongr_connections.pipeline_factory:
          class: %ongr_connections.pipeline_factory.class%
          calls:
              - [ setDispatcher, [ @event_dispatcher ] ]
              - [ setClassName, [ %ongr_connections.pipeline_factory.pipeline_class% ] ]

    # Source event default.
    ongr.pipeline.repository_crawler.repository_source:
       class: %ongr_repository_crawler.crawler.source.class%
       arguments:
           - @es.manager
           - ONGRTestingBundle:Product
       tags:
           - { name: kernel.event_listener, event: ongr.pipeline.repository_crawler.default.source, method: onSource }
