language: php
php:
  - 5.4
  - 5.5
  - 5.6
env:
  - SYMFONY="2.3.*"
services:
  - elasticsearch
before_script:
  - composer update --prefer-dist
script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs -p --standard=PSR2 --ignore=vendor/,Tests/app/ ./
