language: php
php:
  - 5.4
  - 5.5
  - 5.6
env:
  - SYMFONY="2.3.*"
services:
  - elasticsearch
before_script:
  - composer update --prefer-dist
script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/bin/phpcs -p --standard=$TRAVIS_BUILD_DIR/vendor/ongr/ongr-strict-standard/ONGR --ignore=vendor/,Tests/app/ ./
